# Site settings
author: Mercedes Gaillard
title: 
header-img: img/home-bg.png
email: mdg816@googlemail.com
copyright_name: Mercedes Gaillard
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  MercedesDS

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
